### ISSUE TITLE
CORS Issue (Added localhost to Allowed Origins (CORS))

### ISSUE THREAD

**Issue by chasen-bettinger** [jch254/starter-pack#10]
I am trying to learn how your application utilizes redux and auth0 so I cloned the application and tried to get it started. 

![](https://i.imgur.com/7k3sBnS.png)

![](https://i.imgur.com/pU2ZW9y.png)

I keep getting the CORS error though. Any thoughts?

**Comment by jch254** [comment]
Are you still facing this issue? Did you make sure to click save after adjusting the Allowed Origins?

**Comment by chasen-bettinger** [comment]
@jch254 I am not currently facing this issue because I moved on. However, I never got it resolved.
