### ISSUE TITLE
Add .env.example

### ISSUE THREAD

**Issue by Geczy** [jch254/starter-pack#2]
For reference it would be nice to have in the repo

Also, add something like this into loginRequestSaga() ? Or another place? 

```jsx
  if (!process.env.AUTH0_CLIENT_ID || !process.env.AUTH0_DOMAIN) {
    throw new Error('Please define `AUTH0_CLIENT_ID` and `AUTH0_DOMAIN` in your .env file');
  }
```

**Comment by Geczy** [comment]
Recommend https://www.npmjs.com/package/dotenv same as create-react-app

**Comment by jch254** [comment]
I prefer to set environment variables which requires no extra packages or configuration: `AUTH0_CLIENT_ID=YOUR_CLIENT_ID AUTH0_DOMAIN=YOUR_DOMAIN yarn run dev`.

**Comment by jch254** [comment]
Closing as Auth0 Lock already handles this 👍
