### ISSUE TITLE
Convert to using create-react-app?

### ISSUE THREAD

**Issue by Geczy** [jch254/starter-pack#3]
create-react-app includes HMR, dotenv, asset bundling, etc. Is it worth it to use them instead of our own webpack? 

Can save a lot of code, what do you think?

**Comment by Geczy** [comment]
https://github.com/facebookincubator/create-react-app

**Comment by jch254** [comment]
I built this as a starting point for my own web apps and I prefer to have control over the things that create-react-app's curated feature set hides away. I'll create a branch using create-react-app though.

**Comment by Geczy** [comment]
No problem. I made a create-react-app version myself off your branch. Thanks again for your useful base

**Comment by jch254** [comment]
Cheers!
